import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1>
          {" "}
          <Link href="/" className="bg-red-500 p-2 ">
            home
          </Link>
          <Link href="/about" className="bg-red-500 p-2 ">
            about
          </Link>
          <Link href="/contact" className="bg-green-500 p-2">
            Go to Contact
          </Link>
        </h1>
        {children}
        <h2>footer</h2>
      </body>
    </html>
  );
}
